### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by dmike3** [d4v3y0rk/ffpass#9]
/home/user/ffpass/node_modules/node-geocoder/lib/geocoder/geocodiogeocoder.js:14
    throw new Error(this.constructor.name + ' needs an apiKey');
    ^

Error: GeocodioGeocoder needs an apiKey
    at new GeocodioGeocoder (/home/user/ffpass/node_modules/node-geocoder/lib/geocoder/geocodiogeocoder.js:14:11)
    at Object._getGeocoder (/home/user/ffpass/node_modules/node-geocoder/lib/geocoderfactory.js:132:14)
    at Object.getGeocoder (/home/user/ffpass/node_modules/node-geocoder/lib/geocoderfactory.js:218:30)
    at Object.<anonymous> (/home/user/ffpass/index.js:14:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by d4v3y0rk** [comment]
It says in the readme you need an api key for the location stuff to work...

**Comment by dmike3** [comment]
> It says in the readme you need an api key for the location stuff to work...

If I'm not mistaken, this is options. Is something supposed to be commented out?

**Comment by dmike3** [comment]
> It says in the readme you need an api key for the location stuff to work...

So I registered and got an API key. Added it to the env variables and I'm getting the following error.

(node:126) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
    at Promise (/home/niter3/ffpass/node_modules/ffpass/index.js:29:33)
    at new Promise (<anonymous>)
    at vehicle.auth (/home/niter3/ffpass/node_modules/ffpass/index.js:18:16)
    at main (/home/niter3/ffpass/index.js:23:15)
    at Object.<anonymous> (/home/niter3/ffpass/index.js:66:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by d4v3y0rk** [comment]
`Object.fromEntries()` is new-ish in nodejs. You need to be running at least version 12 I believe. Sounds like you are running an earlier version of node.

**Comment by dmike3** [comment]
> `Object.fromEntries()` is new-ish in nodejs. You need to be running at least version 12 I believe. Sounds like you are running an earlier version of node.

Bingo! That was it. 

Any chance to add a list of required packages on your github page? Including version numbers for others to see?

**Comment by d4v3y0rk** [comment]
That information is in the package.json file in the repo.

**Comment by dmike3** [comment]
> That information is in the package.json file in the repo.
> […](#)
> On Sep 4, 2020, at 8:27 AM, dmike3 ***@***.***> wrote: ﻿ Object.fromEntries() is new-ish in nodejs. You need to be running at least version 12 I believe. Sounds like you are running an earlier version of node. Bingo! That was it. Any chance to add a list of required packages on your github page? Including version numbers for others to see? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Okay.

> That information is in the package.json file in the repo.
> […](#)
> On Sep 4, 2020, at 8:27 AM, dmike3 ***@***.***> wrote: ﻿ Object.fromEntries() is new-ish in nodejs. You need to be running at least version 12 I believe. Sounds like you are running an earlier version of node. Bingo! That was it. Any chance to add a list of required packages on your github page? Including version numbers for others to see? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks again for this work! Awesome stuff!

**Comment by dmike3** [comment]
> That information is in the package.json file in the repo.
> […](#)
> On Sep 4, 2020, at 8:27 AM, dmike3 ***@***.***> wrote: ﻿ Object.fromEntries() is new-ish in nodejs. You need to be running at least version 12 I believe. Sounds like you are running an earlier version of node. Bingo! That was it. Any chance to add a list of required packages on your github page? Including version numbers for others to see? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks again for this awesome work!
